version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http api:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - api