services:
  api:
    build: .
    container_name: marina_api
    ports:
      - "8000:8000"
  
  ngrok:
    image: ngrok/ngrok:latest
    command: http api:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - api